<a href="https://colab.research.google.com/github/jihyunjeongme/deeplearning-tensflow-3min/blob/master/%5B%EA%B3%A8%EB%B9%88%ED%95%B4%EC%BB%A4%EC%9D%98_3%EB%B6%84_%EB%94%A5%EB%9F%AC%EB%8B%9D%5D_Ch3_%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C_%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# 개념정리

# 텐서(tensor)
# 플레이스홀더(placeholder)
# 변수(variable)

In [2]:
import tensorflow as tf
print(tf.__version__)

1.13.1


In [4]:
# tf.constant로 상수를 hello 변수에 저장

hello = tf.constant('Hello,TensorFlow!')
print(hello)                    

Tensor("Const_1:0", shape=(), dtype=string)


In [0]:
# 랭크(Rank)
  # 랭크가 0이면 스칼라, 1이면 벡터, 2면 행렬 3 이상이면 n-Tensor 또는 n차원 텐서
# 셰이프(Shape)
  # 각 차원의 요소 개수로, 텐서의 구조를 설명

In [6]:
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a,b)
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [0]:
# 텐서플로 프로그램의 구조가 다음의 두 가지로 분리되어 있음
  # 1. 그래프 생성
  # 2. 그래프 실행
  
# 그래프: 텐서들의 연산 모음
# 지연실행: 텐서와 텐서의 연산들을 먼저 정의하여 그래프를 만들고, 이후 필요할 때 연산을 실행하는 코드를 넣어 실행

In [9]:
# 그래프의 실행은 Session 안에서 이뤄져야 하며, 다음과 같이 Session 객체와 run 메서드를 이용

sess = tf.Session()

print(sess.run(hello))
print(sess.run([a,b,c]))

sess.close()

b'Hello,TensorFlow!'
[10, 32, 42]


In [0]:
# 3.2 플레이스홀더와 변수
# 플레이스 홀더: 그래프에 사용할 입력값을 나중에 받기 위해 사용하는 매개변수
# 변수: 그래프를 최적화 하는 용도로 텐서플로가 학습한 결과를 갱신하기 위해 사용하는 변수

In [11]:
# 플레이스 홀더는 다음과 같이 사용

# None은 크기가 정해지지 않았음을 의미합니다.
X = tf.placeholder(tf.float32,[None,3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [0]:
# Placeholder라는 (?, 3) 모양의 float32 자료형을 가진 텐서가 생성됨

In [0]:
x_data = [[1,2,3],[4,5,6]]

In [14]:
# 다음은 W,b 변수들을 정의
# W는 [3,2] 행렬 형태
# b는 [2,1] 행렬 형태의 텐서로 tf.random_normal 함수를 이용해 정규분포의 무작위 값으로 초기화

W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

Instructions for updating:
Colocations handled automatically by placer.


In [0]:
# 물론 이와 같이 직접 원하는 텐서의 형태의 데이터를 만들어서 넣어 줄 수도 있음.

W = tf.Variable([[0.1,0.1], [0.2, 0.2], [0.3, 0.3]])

In [0]:
# 다음으로 입력값과 변수들을 계산할 수식을 작성
# W와 X가 행렬이기 떄문에 tf.matmul 함수를 사용해야 함.
# 행렬이 아닌 경우에는 단순히 곱셈 연산자(*)나 tf.mul 함수를 사용

expr = tf.matmul(X,W) + b

In [0]:
# 행렬곱
  # 행렬곱 A x B에 대하여, 행렬 A의 열 수와 행렬 B의 행수는 같아야 함
  # 행렬곱 A x B를 계산한 행렬 AB의 크기는 A의 행 개수와 B의 열개수가 된다.
  

In [18]:
# 설정한 텐서들과 계산된 그래프의 결과를 확인해 보겠습니다.

sess = tf.Session()

# 앞에 정의한 변수들을 초기화
sess.run(tf.global_variables_initializer()) 

print("=== x_data===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")

# feed_dict: 그래프를 실행 할 떄 사용할 입력값 지정
print(sess.run(expr, feed_dict={X: x_data})) 

sess.close()

=== x_data===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[0.1 0.1]
 [0.2 0.2]
 [0.3 0.3]]
=== b ===
[[0.34432825]
 [0.25913268]]
=== expr ===
[[1.7443284 1.7443284]
 [3.4591327 3.4591327]]


In [0]:
# expr 수식에는 X, W, b를 사용했는데, 이중 X가 플레이스홀더라 X에 값을 넣어주지 않으면
# 계산에 사용할 값이 없으므로 에러
# 따라서 미리 정의해둔 x_data를 X 값으로 넣음.

In [0]:
# 3.3 선형 회귀 모델 구현하기
  # 선형 회귀: 주어진 x와 y값을 가지고 서로간의 관계를 파악하는 것

In [0]:
# 텐서플로의 최적화 함수를 이용해 X와 Y의 상관관계를 분석하는 기초적인 선형 회귀 모델

x_data = [1,2,3]
y_data = [1,2,3]

In [0]:
# x와 y의 상관관계를 설명하기 위한 변수들인 W와 b를 각각 -1.0부터 0.1 사이의 균등분포를 가진 무작위값으로 초기화

W = tf.Variable(tf.random_uniform([1], -1.0,1.0))
b = tf.Variable(tf.random_uniform([1], -1.0,1.0))

In [0]:
# 자료를 입력 받을 플레이스 홀더 설정

X = tf.placeholder(tf.float32, name="X")
Y = tf.placeholder(tf.float32, name="Y")

In [0]:
# X와 Y의 상관관계(선형관계)를 분석하기 위한 수식 작성
# W와의 곱과 b와의 합을 통해 X와 Y의 관계를 설명하겠다.
# 즉, X가 주어졌을 때 Y를 만들어 낼 수 있는 W와 b를 찾아내겠다.
# W 가중치, b는 편향

hypothesis = W * X + b

In [0]:
# 손실함수 작성
# 손실함수: 한 쌍(x, y)의 데이터에 대한 손실값을 계산하는 함수
# 손실값: 실제값과 모델로 예측한 값이 얼마나 차이가 나는가를 나타내는 값

# 즉, 손실값이 작을수록 그 모델이 X와 Y의 관계를 잘 설명하고 있다는 뜻
# 주어진 X 값에 대한 Y값을 정확하게 예측 할 수 있다라는 뜻

# 비용: 이 손실을 전체 데이터에 대해 구한 경우
# 학습: 변수들의 값을 다양하게 넣어 계산해보면서 이 손실값을 최소화하는 W와 b의 값을 구하는 것
# 손실 값으로 '예측값과 실제값의 거리'를 가장 많이 사용함. 우리도 이를 사용
# 즉, 손실값은 예측값에서 실제값을 뺸 뒤 제곱하여, 그리고 비용은 모든 데이터에 대한 손실값의 평균을 내어 구함

cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [0]:
# 경사하강법 최적화 함수를 이용해 손실값을 최소화하는 연산 그래프를 생성
# 경사하강법: 최적화 방법 중 가장 기본적인 알고리즘, 함수의 기울기를 구하고 기울기가 낮은 쪽으로 계속 이동
# 시키면서 최적의 값을 찾아 나가는 방법

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train_op = optimizer.minimize(cost)

In [0]:
# 최적화 함수: 가중치와 편향 값을 변경해가면서 손실값을 최소화하는 가장 최적화된 가중치와 편향 값을
# 찾아주는 함수
# learning_rate: 최적화 함수의 매개변수, 학습률은 얼마나 '급하게' 할것인가를 설정하는 것
# 값이 너무 크면 최적의 손실값을 찾지 못하고 지나치게 되고
# 값이 너무 작으면 학습 속도가 매우 느려집니다.
# 하이퍼파라미터 : 학습을 진행하는 과정에 영향을 주는 변수
# 이를 잘 튜닝하는 것이 큰 과제

In [33]:
# 이제 선형 회귀 모델을 다 만들었으니, 그래프를 실행해 학습 시키고 결과 확인
# 세션을 생성하고 변수들을 초기화
# 파이썬 with 기능을 이용해 세션 블록을 만들고 세션 종료를 자동으로 처리

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())

# 다음은 최적화를 수행하는 그래프인 train_op를 실행
# 실행 시마다 변화하는 손실값을 출력
# 학습은 100번 수행, feed_dict 매개변수 통해, 상관관계를 알아내고자 하는 데이터인 x_data와 y_data입력

  for step in range(100):
    _, cost_val = sess.run([train_op,cost], feed_dict={X: x_data, Y: y_data})
    
    print(step, cost_val, sess.run(W), sess.run(b))

0 0.058320478 [0.8038681] [0.42569074]
1 0.026762506 [0.81664824] [0.41900533]
2 0.025147399 [0.8201744] [0.40854496]
3 0.02394876 [0.82459366] [0.39876622]
4 0.022811107 [0.8287997] [0.3891755]
5 0.021727594 [0.8329165] [0.37982053]
6 0.020695513 [0.83693284] [0.3706898]
7 0.019712456 [0.8408529] [0.3617787]
8 0.018776096 [0.84467876] [0.35308182]
9 0.017884245 [0.8484126] [0.34459397]
10 0.017034696 [0.85205656] [0.33631015]
11 0.01622554 [0.855613] [0.3282255]
12 0.015454836 [0.859084] [0.3203352]
13 0.014720727 [0.8624716] [0.3126346]
14 0.014021468 [0.8657777] [0.30511907]
15 0.013355446 [0.86900425] [0.29778418]
16 0.012721047 [0.8721533] [0.29062566]
17 0.012116789 [0.8752267] [0.28363922]
18 0.011541235 [0.8782261] [0.2768207]
19 0.01099301 [0.88115346] [0.2701661]
20 0.010470829 [0.8840105] [0.2636715]
21 0.009973463 [0.8867988] [0.257333]
22 0.009499707 [0.88952005] [0.2511469]
23 0.009048484 [0.8921759] [0.24510951]
24 0.008618662 [0.8947679] [0.23921724]
25 0.008209264 [0.8

In [0]:
# 위와 같이 손실값이 점점 줄어든다면 학습이 정상적으로 이뤄지고 있는것

In [37]:
# 학습에 사용되지 않았던 값인 5와 2.5를 X값으로 넣고 결과를 확인

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())

  for step in range(100):
    _, cost_val = sess.run([train_op,cost], feed_dict={X: x_data, Y: y_data})
    
    print(step, cost_val, sess.run(W), sess.run(b))
    
  print("\n=== Test ===")
  print("X:5, Y:", sess.run(hypothesis, feed_dict={X: 5}))
  print("X:2.5, Y:", sess.run(hypothesis, feed_dict={X: 2.5}))

0 4.4288564 [1.2805442] [-0.3959802]
1 0.07973071 [1.177095] [-0.42900184]
2 0.026505237 [1.1834071] [-0.4140395]
3 0.02465568 [1.1778429] [-0.40459442]
4 0.02347745 [1.173694] [-0.39481267]
5 0.022362173 [1.1695046] [-0.38532773]
6 0.021299936 [1.1654314] [-0.37606403]
7 0.020288175 [1.1614544] [-0.36702377]
8 0.019324483 [1.1575731] [-0.3582008]
9 0.018406542 [1.1537852] [-0.34958985]
10 0.017532224 [1.1500883] [-0.341186]
11 0.016699433 [1.1464803] [-0.3329841]
12 0.01590619 [1.142959] [-0.3249794]
13 0.015150647 [1.1395223] [-0.3171671]
14 0.0144309765 [1.1361684] [-0.30954263]
15 0.0137454895 [1.132895] [-0.30210143]
16 0.0130925765 [1.1297002] [-0.29483914]
17 0.012470665 [1.1265824] [-0.28775138]
18 0.011878297 [1.1235394] [-0.28083405]
19 0.011314083 [1.1205696] [-0.27408302]
20 0.010776632 [1.1176713] [-0.26749423]
21 0.010264748 [1.1148424] [-0.2610639]
22 0.009777174 [1.1120818] [-0.2547881]
23 0.009312744 [1.1093874] [-0.24866317]
24 0.008870385 [1.1067578] [-0.2426855]
25 

In [0]:
# 기대한 대로 X가 5일 때는 Y값으로 5를, 2.5 일때는 2.5를 정확히 예측해 냈습니다.